steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 'us-central1-docker.pkg.dev/nodal-deck-481823-e8/vangarments-repo/frontend:latest', 
    '--build-arg', 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}',
    '-f', 'packages/web/Dockerfile', 
    '.'
  ]
images:
- 'us-central1-docker.pkg.dev/nodal-deck-481823-e8/vangarments-repo/frontend:latest'
substitutions:
  _NEXT_PUBLIC_API_URL: 'http://localhost:3001/api/v1' # Default, will be overridden
